### ISSUE TITLE
StepperBase "stop()" method should not call moveRelSteps()

### ISSUE THREAD

**Issue by paul-lebel** [czbiohub/PyMotors#6]
StepperBase implements a strange and not widely compatible stop() method, by calling self.moveRelSteps(0). Most controllers have an independent 'stop()' or similar command such as 'halt()', which is different than moving to a relative position. 

There are problems with calling a moveRel type command when trying to stop:
1) Stop, or Halt, usually implies an immediate braking action. Issuing a moveRel type command on the other hand, instead invokes a motion profiler with a given acceleration. 
2) Calling stop() when the motor is already disabled issues a warning because the motor tries to 'move' to the current position, but it's in fact disabled and can't move. Calling stop() on a disabled motor should just do nothing.

**Comment by robertpuccinelli** [comment]
StepperBase has no notion of acceleration or deceleration, so calling the stop method causes the motor to stop moving immediately. In the case of a Tic board where there is acceleration, a halt method has since been implemented that stops the motor immediately at the expense of raising a "Position Uncertain" flag in the hardware. Additionally, the StepperBase movement commands now include a check a flag prior to moving to confirm that the device is enabled. If not, no movement commands will be issued to the hardware. Thanks for the feedback!
